## 예외 투명성

예외 투명성(Exception Transparency)은 주로 소프트웨어 개발 및 설계 원칙에서 나오는 개념으로, 소프트웨어 모듈이나 서브루틴이 자신에게 주어진 작업을 완료할 수 없을 때, 그 모듈이나 서브루틴이 그
사실을 명확하게 나타내야 한다는 원칙을 의미합니다.

이 원칙은 일반적으로 예외를 "투명하게" 처리해야 한다는 의미로 해석됩니다. 즉, 함수나 메서드는 예외를 적절히 처리하거나, 다른 코드에게 예외를 전달하여 처리하도록 할 수 있어야 합니다. 이것은 다른 코드(특히
호출자)가 예외를 인지하고 적절하게 대응할 수 있도록 하기 위함입니다.

예외 투명성은 "묵시적 실패"와 대조되는 개념입니다. 묵시적 실패란 함수나 메서드가 실패하였음에도 불구하고 그 사실을 호출자에게 명확하게 알리지 않는 상황을 의미합니다. 이런 경우 호출자는 실패한 작업의 결과를 잘못
이해하거나, 오류의 원인을 파악하기 어렵게 됩니다.

예외 투명성 원칙을 따르면, 코드의 안정성과 예측 가능성이 향상되며, 오류를 발견하고 수정하는 데 필요한 시간이 줄어듭니다. 그러나 이 원칙을 적용하는 방법은 프로그래밍 언어와 프레임워크, 그리고 특정 어플리케이션의
요구사항에 따라 다르게 될 수 있습니다.

```kotlin
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*

fun simple(): Flow<String> =
        flow {
            for (i in 1..3) {
                println("Emitting $i")
                emit(i) // emit next value
            }
        }
                .map { value ->
                    check(value <= 1) { "Crashed on $value" }
                    "string $value"
                }

fun main() = runBlocking<Unit> {
    simple()
            .catch { e -> emit("Caught $e") } // emit on exception
            .collect { value -> println(value) }
}
```

## catch 투명성

Flow에서의 catch 연산자는 오류를 처리하는 데 사용되며, 이 연산자는 'catch 투명성' 원칙에 따라 동작합니다. 즉, catch 연산자는 업스트림에서 발생한 예외만 잡아내고 처리하며, 다운스트림(즉,
catch 연산자 이후의 코드)에는 영향을 미치지 않습니다.

이런 방식으로, catch 연산자는 오류를 인지하고 처리하는 동시에, 그 오류가 다운스트림의 동작에 영향을 미치는 것을 방지합니다. 이로써 각 Flow 연산자는 자신의 동작 범위 내에서만 오류를 관리하고, 그 외의
영역은 그대로 유지되는, 투명성을 유지하게 됩니다.

```kotlin
flow {
    emit(1)
    throw RuntimeException()
}
        .catch { e -> emit("Caught $e") }  // 업스트림에서의 오류를 잡아냅니다.
        .collect { value -> println(value) }  // 다운스트림에서 collect는 예외에 영향받지 않습니다.

```

이 코드에서, `catch` 연산자는 업스트림에서 발생한 `RuntimeException`을 잡아낸다.

그러나 이 오류는 `collect`연산자에는 영향을 미치지 않는다. 따라서 이 예외는 투명하게 처리되며, 이로써 각각의 Flow 연산자는 자신의 동작 범위 내에서만 오류를 관리하게 된다.

